### ISSUE TITLE
Video version?

### ISSUE THREAD

**Issue by tomdevlive** [aloproducao/pad-dj-for-lives#1]
This is a great app and cool concept. Would it be possible to have a video version that acted the same way, but when you click the upload it plays the video out to an address or via NDI?

**Comment by aloproducao** [comment]
Hello!

That's a good question you've raised. We can consider integrating with vdo.ninja or vingester to support NDI streaming. Do you have any specific suggestions or ideas for the interface?

Looking forward to your feedback. Thank you!

**Comment by aloproducao** [comment]
> This is a great app and cool concept. Would it be possible to have a video version that acted the same way, but when you click the upload it plays the video out to an address or via NDI?

Hello!

That's a good question you've raised. We can consider integrating with vdo.ninja or vingester to support NDI streaming. Do you have any specific suggestions or ideas for the interface?

Looking forward to your feedback. Thank you!

**Comment by aloproducao** [comment]
https://videopad.vercel.app/

create for videos
